from collections.abc import Mapping
from typing import Any, Literal

from django.conf import settings

import requests


class GraphClient:
    def __init__(self, token=None):
        self.tenant_id = settings.MSGRAPH_API_BACKEND_TENANT_ID
        self.client_id = settings.MSGRAPH_API_BACKEND_CLIENT_ID
        self.client_secret = settings.MSGRAPH_API_BACKEND_CLIENT_SECRET
        self.base_url = "https://graph.microsoft.com/v1.0"
        self.token = token

    def _get(self, url: str):
        """
        Sends a GET request to the specified URL and retrieves the response.

        :param url: The URL to which the GET request will be sent.
        :return: The response from the GET request.
        """

        return self._request("GET", url)

    def _patch(self, url: str, json: Mapping[str, Any]):
        """
        Sends a PATCH request to the specified URL with the provided data.

        This method is used internally to handle PATCH requests by invoking the
        generic `_request` method with the method type set to "PATCH". The provided
        URL and data are passed as arguments to the request.

        :param url: The endpoint URL to which the PATCH request is sent.
        :param json: A mapping of the data to be included in the body of the PATCH
            request.
        :return: The response generated by the `_request` method upon completing the
            PATCH request.
        """
        return self._request("PATCH", url, json)

    def _post(self, url: str, json: Mapping[str, Any]):
        """
        Sends an HTTP POST request to the specified URL with the provided data.

        This internal method is a helper function for making POST requests. It handles
        the communication protocol for submitting data to the server via POST.

        :param url: The target URL to which the POST request will be sent.
        :param json: A mapping of data payload to be sent in the POST request. This
            typically contains key-value pairs.
        :return: The response from the server after processing the POST request.
        """
        return self._request("POST", url, json)

    def _request(
        self,
        method: Literal["GET", "PATCH", "POST", "PUT"],
        path_or_url: str,
        json: Mapping[str, Any] | None = None,
        data: bytes | None = None,
        extra_headers: Mapping[str, str] | None = None,
        raw_response: bool = False,
        force_default_headers: bool = False,
    ):
        """
        Performs an HTTP request using the specified method to the given URL with optional data
        and headers. This function supports both JSON data and raw byte data, as well as the
        option to return either the parsed JSON response or the raw HTTP response object.

        The default headers are only used if `path_or_url` is not a URL (does not start with "http://" or "https://").

        :param method: The HTTP method to use for the request ("GET", "PATCH", "POST", "PUT").
        :param path_or_url: The path or URL to send the request to.
        :param data: Optional data to include in the request body. Can be a mapping for JSON data
            or raw bytes for other formats.
        :param extra_headers: Additional headers to include in the request. Merges with any
            default headers.
        :param raw_response: If True, returns the raw HTTP response object. If False, returns the
            parsed JSON response.
        :param force_default_headers: If True, The default headers are used even if the `path_or_url`
            is a URL.
        :return: Either the parsed JSON response or the raw HTTP response object, depending on
            the `raw_response` parameter.
        """
        url = (
            path_or_url
            if path_or_url.startswith(("http://", "https://"))
            else f"{self.base_url.rstrip('/')}/{path_or_url.lstrip('/')}"
        )
        headers = self._get_headers(path_or_url, extra_headers, force_default_headers)

        response = requests.request(
            method,
            url,
            headers=headers,
            json=json,
            data=data,
        )

        response.raise_for_status()
        if not raw_response:
            data = response.json()
            return data
        return response

    def _get_headers(
        self,
        path_or_url: str,
        extra_headers: Mapping[str, str] | None = None,
        force_default_headers=False,
    ) -> Mapping[str, str]:
        """
        Generates a combined set of HTTP headers, merging user-provided extra headers with
        default headers such as Authorization and Content-Type. The Authorization header
        is automatically populated based on the instance's token.

        The default headers are only used if `path_or_url` is not a URL (does not start with "http://" or "https://").

        :param path_or_url: The path or URL to send the request to.
        :param extra_headers: A dictionary containing additional headers to be merged.
        :return: A dictionary containing the merged set of headers, including the default
            Authorization and Content-Type headers.
        """
        default_headers = (
            {}
            if path_or_url.startswith(("http://", "https://"))
            and not force_default_headers
            else {
                "Authorization": f"Bearer {self.token}",
                "Content-Type": "application/json",
            }
        )

        return {
            **default_headers,
            **(extra_headers or {}),
        }
