# DISCLAIMER: THIS IS FOR DEVELOPMENT PURPOSES ONLY AND NOT SUITABLE FOR PRODUCTION.

x-labels: &x-labels
  client: dev
  target: test
  app: "opendms"

x-app-env: &x-app-env
  - DJANGO_SETTINGS_MODULE=opendms.conf.docker
  - SECRET_KEY=${SECRET_KEY:-django-insecure-kex=ipoau_q(o_w=6bd8q6_sb2#xgkdbknq4m&hl2jtx(7#n_}
  - DB_NAME=opendms
  - DB_USER=opendms
  - DB_HOST=db
  # Only allow all hosts for development/testing purposes!
  - ALLOWED_HOSTS=*
  - STATIC_ROOT_VOLUME=/srv/static/
  - CACHE_DEFAULT=redis:6379/0
  - CACHE_AXES=redis:6379/0
  - CELERY_BROKER_URL=redis://redis:6379/1
  - CELERY_RESULT_BACKEND=redis://redis:6379/1
  - DISABLE_2FA=true
  # Environment labeling
  - SHOW_ENVIRONMENT=yes
  - ENVIRONMENT_LABEL=docker-compose
  - ENVIRONMENT_BACKGROUND_COLOR=#1d63ed
  - ENVIRONMENT_FOREGROUND_COLOR=white
  # Enabling Open Telemetry requires a target to send telemetry towards!
  - OTEL_SDK_DISABLED=${OTEL_SDK_DISABLED:-true}
  - OTEL_RESOURCE_ATTRIBUTES=maykin.saas.client=maykin,maykin.saas.target=dev
  - OTEL_METRIC_EXPORT_INTERVAL=${OTEL_METRIC_EXPORT_INTERVAL:-60000}
  - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://otel-collector:4317}  # gRPC
  # otel:supersecret, escape spaces and = with percent encoding
  # - OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic b3RlbDpzdXBlcnNlY3JldA==
  - OTEL_EXPORTER_OTLP_METRICS_INSECURE=${OTEL_EXPORTER_OTLP_METRICS_INSECURE:-true}
  - _OTEL_ENABLE_CONTAINER_RESOURCE_DETECTOR=true
  # ES settings
  - INIT_ES_INDICES=true
  - ELASTICSEARCH_HOST=http://es:9200/
  - ELASTICSEARCH_USER=elastic
  - ELASTICSEARCH_PASSWORD=insecure-elastic

x-app-volumes: &x-app-volumes
  - static:/srv/static
  - media:/app/media

services:
  db:
    image: postgres:${PG_VERSION:-17}
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - open-dms-dev

  redis:
    image: redis:8
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 1s
      retries: 3
    networks:
      - open-dms-dev

  # Based on https://www.elastic.co/guide/en/elasticsearch/reference/current/run-elasticsearch-locally.html
  # Log in with `elastic` / `insecure-elastic` (or whatever you set the envvar `ES_PASSWORD` to).
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION:-8.17.1}
    environment:
      - discovery.type=single-node
      - cluster.name=opendms-dev
      - node.name=es01
      - node.roles=master,data,ingest
      - ingest.geoip.downloader.enabled=false
      - ELASTIC_PASSWORD=${ES_PASSWORD:-insecure-elastic}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      # - xpack.license.self_generated.type=trial
      - xpack.ml.use_auto_machine_memory_percent=true
      - ES_JAVA_OPTS=-Xms${ES_HEAP_INIT:-128m} -Xmx${ES_HEAP_MAX:-2g}
      - cluster.routing.allocation.disk.watermark.low=${ES_DISK_SPACE_REQUIRED:-1gb}
      - cluster.routing.allocation.disk.watermark.high=${ES_DISK_SPACE_REQUIRED:-1gb}
      - cluster.routing.allocation.disk.watermark.flood_stage=${ES_DISK_SPACE_REQUIRED:-1gb}
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --output /dev/null --silent --head --fail -u elastic:${ES_PASSWORD:-insecure-elastic} http://es:9200",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 9200:9200
      # - "9300:9300"

  prepare-volumes:
    image: busybox
    command: /bin/chown -R 1000 /srv/static
    volumes:
      - static:/srv/static

  web:
    build: .
    image: maykinmedia/opendms:${TAG:-latest}
    environment: *x-app-env
    volumes: *x-app-volumes
    healthcheck:
      test: ["CMD-SHELL", "maykin-common health-check"]
      interval: 30s
      timeout: 5s
      retries: 5
    labels:
      <<: *x-labels
      service: web
    ports:
      - 8000:8000
    depends_on:
      - prepare-volumes
      - db
      - redis
      - es
    networks:
      - open-dms-dev

  celery:
    image: maykinmedia/opendms:${TAG:-latest}
    environment: *x-app-env 
    command: /celery_worker.sh
    healthcheck:
      test: ["CMD", "python", "/app/bin/check_celery_worker_liveness.py"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes: *x-app-volumes 
    depends_on:
      - db
      - redis
    networks:
      - open-dms-dev

  celery-beat:
    image: maykinmedia/opendms:${TAG:-latest}
    environment: *x-app-env 
    command: /celery_beat.sh
    depends_on:
      - redis
      - celery
    networks:
      - open-dms-dev

  celery-flower:
    image: maykinmedia/opendms:${TAG:-latest}
    environment: *x-app-env 
    command: /celery_flower.sh
    ports:
      - 5555:5555
    depends_on:
      - redis
      - celery
    networks:
      - open-dms-dev

volumes:
  db:
  static:
  media:
  es-data:

networks:
  open-dms-dev:
    name: open-dms-dev
