# Generated by Django 5.2.11 on 2026-03-05 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "zgw_consumers",
            "0027_service_oauth2_scope_service_oauth2_token_url_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ZGWApiGroupConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A recognisable name for this set of ZGW APIs.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "identifier",
                    models.SlugField(
                        help_text="A unique, human-friendly identifier to identify this group.",
                        unique=True,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "drc_service",
                    models.ForeignKey(
                        limit_choices_to={"api_type": "drc"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zgwset_drc_config",
                        to="zgw_consumers.service",
                        verbose_name="Documenten API",
                    ),
                ),
                (
                    "zrc_service",
                    models.ForeignKey(
                        limit_choices_to={"api_type": "zrc"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zgwset_zrc_config",
                        to="zgw_consumers.service",
                        verbose_name="Zaken API",
                    ),
                ),
                (
                    "ztc_service",
                    models.ForeignKey(
                        limit_choices_to={"api_type": "ztc"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zgwset_ztc_config",
                        to="zgw_consumers.service",
                        verbose_name="Catalogi API",
                    ),
                ),
            ],
            options={
                "verbose_name": "ZGW API groups",
                "verbose_name_plural": "ZGW API groups",
            },
        ),
    ]
