# Generated by Django 5.2.11 on 2026-02-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, verbose_name='token')),
                ('contact_person', models.CharField(blank=True, help_text='Name of the person to contact about this application and the associated credentials.', max_length=200, verbose_name='contact person')),
                ('email', models.EmailField(blank=True, help_text='Email of the person to contact about this application and the associated credentials.', max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, help_text='Phonenumber of the person contact about this application and the associated credentials.', max_length=128, verbose_name='phone number')),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Last date when the token was modified', verbose_name='last modified')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date when the token was created', verbose_name='created')),
            ],
            options={
                'verbose_name': 'application API key',
                'verbose_name_plural': 'application API keys',
            },
        ),
    ]
