/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * login
         * @description Authenticates the user, returns whoami details on successful login.
         */
        post: operations["apiV1AccountsLoginCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * logout
         * @description Remove the authenticated user's ID from the request and flush their session data.
         */
        get: operations["apiV1AccountsLogoutRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * whoami
         * @description Returns the current logged in user.
         */
        get: operations["apiV1AccountsWhoamiRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description Search the document records.
         */
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1ServicesList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/informatieobjecttypen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1ServicesInformatieobjecttypenList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/informatieobjecttypen/{informatieobjecttypeUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1ServicesInformatieobjecttypenRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/statustypen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * statustypenList
         * @description Read-only endpoint voor STATUSTYPEn
         */
        get: operations["apiV1ServicesStatustypenList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/statustypen/{statustypeUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * statustypenRetrieve
         * @description Read-only endpoint voor STATUSTYPEn
         */
        get: operations["apiV1ServicesStatustypenRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaakinformatieobjecten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1ServicesZaakinformatieobjectenList"];
        put?: never;
        /** zaakinformatieobjectCreate */
        post: operations["apiV1ServicesZaakinformatieobjectenCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaakinformatieobjecten/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1ServicesZaakinformatieobjectenRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaaktypen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * zaaktypenList
         * @description Exposes Zaaktypen from /services/<zgw-service>/zaaktypen
         */
        get: operations["apiV1ServicesZaaktypenList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaaktypen/{zaaktypeUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * zaaktypenRetrieve
         * @description Exposes Zaaktypen from /services/<zgw-service>/zaaktypen
         */
        get: operations["apiV1ServicesZaaktypenRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaaktypen/{zaaktypenZaaktypeUuid}/statustypen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * statustypenList
         * @description Read-only endpoint voor alle STATUSTYPEn die mogelijk zijn voor een bepaald ZAAKTYPE.
         */
        get: operations["apiV1ServicesZaaktypenStatustypenList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaaktypen/{zaaktypenZaaktypeUuid}/statustypen/{statustypeUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * statustypenRetrieve
         * @description Read-only endpoint voor alle STATUSTYPEn die mogelijk zijn voor een bepaald ZAAKTYPE.
         */
        get: operations["apiV1ServicesZaaktypenStatustypenRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaaktypen/{zaaktypenZaaktypeUuid}/zaken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * zakenList
         * @description Exposes Zaak from /services/<zgw-service>/zaaktypen/<zaaktype>/zaken
         */
        get: operations["apiV1ServicesZaaktypenZakenList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaaktypen/{zaaktypenZaaktypeUuid}/zaken/{zaakUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * zakenRetrieve
         * @description Exposes Zaak from /services/<zgw-service>/zaaktypen/<zaaktype>/zaken
         */
        get: operations["apiV1ServicesZaaktypenZakenRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaaktypen/{zaaktypenZaaktypeUuid}/zaken/{zakenZaakUuid}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * documentsList
         * @description Exposes Documents from /services/<zgw-service>/zaaktypen/<zaaktype>/zaken/<zaak>/documents
         */
        get: operations["apiV1ServicesZaaktypenZakenDocumentsList"];
        put?: never;
        /**
         * documentsCreate
         * @description Exposes Documents from /services/<zgw-service>/zaaktypen/<zaaktype>/zaken/<zaak>/documents
         */
        post: operations["apiV1ServicesZaaktypenZakenDocumentsCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaaktypen/{zaaktypenZaaktypeUuid}/zaken/{zakenZaakUuid}/documents/{documentUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * documentsRetrieve
         * @description Exposes Documents from /services/<zgw-service>/zaaktypen/<zaaktype>/zaken/<zaak>/documents
         */
        get: operations["apiV1ServicesZaaktypenZakenDocumentsRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaaktypen/{zaaktypenZaaktypeUuid}/zaken/{zakenZaakUuid}/documents/{documentUuid}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * documentsDownload
         * @description Download de binaire data van het (ENKELVOUDIG) INFORMATIEOBJECT.
         */
        get: operations["documentDownload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaaktypen/{zaaktypenZaaktypeUuid}/zaken/{zakenZaakUuid}/documents/{documentUuid}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * documentsEdit
         * @description Een document met binaire gegevens bewerken op OneDrive
         */
        get: operations["documentEdit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaaktypen/{zaaktypenZaaktypeUuid}/zaken/{zakenZaakUuid}/documents/{documentUuid}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * documentsUpload
         * @description Een nieuwe versie van een document uploaden naar OpenZaak
         */
        get: operations["documentUpload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * serviceZakenList
         * @description Exposes Zaak from /services/<zgw-service>/zaaktypen/<zaaktype>/zaken
         */
        get: operations["apiV1ServicesZakenList"];
        put?: never;
        /**
         * serviceZakenCreate
         * @description Exposes Zaak from /services/<zgw-service>/zaaktypen/<zaaktype>/zaken
         */
        post: operations["apiV1ServicesZakenCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaken/{zaakUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * serviceZakenRetrieve
         * @description Exposes Zaak from /services/<zgw-service>/zaaktypen/<zaaktype>/zaken
         */
        get: operations["apiV1ServicesZakenRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1ServicesRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oidc/callback/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Microsoft authentication callback
         * @description Callback endpoint voor Microsoft OAuth authenticatie.
         */
        get: operations["oidcCallbackRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Webhook callback
         * @description Endpoint webhook che riceve notifiche dal backend document_edit.
         */
        post: operations["webhookCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Auth: {
            username: string;
            password: string;
        };
        CheckListItem: {
            /** @description De betekenisvolle benaming van het checklistitem */
            itemnaam: string;
            /** @description Beschrijving van de overwegingen bij het controleren van het aandachtspunt */
            toelichting?: string | null;
            /** @description Een betekenisvolle vraag waaruit blijkt waarop het aandachtspunt gecontroleerd moet worden. */
            vraagstelling: string;
            /** @description Het al dan niet verplicht zijn van controle van het aandachtspunt voorafgaand aan het bereiken van de status van het gerelateerde STATUSTYPE. */
            verplicht: boolean;
        };
        Document: {
            /** @description Unieke resource identifier (UUID4) */
            uuid: string;
            /**
             * Format: uri
             * @description URL-referentie naar dit object. Dit is de unieke identificatie en locatie van dit object.
             */
            url: string;
            /** @description Een binnen een gegeven context ondubbelzinnige referentie naar het INFORMATIEOBJECT. */
            identificatie: string;
            /** @description Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die het informatieobject heeft gecreëerd of heeft ontvangen en als eerste in een samenwerkingsketen heeft vastgelegd. */
            bronorganisatie: string;
            /**
             * Format: date
             * @description Een datum of een gebeurtenis in de levenscyclus van het INFORMATIEOBJECT.
             */
            creatiedatum: string;
            /** @description De naam waaronder het INFORMATIEOBJECT formeel bekend is. */
            titel: string;
            /** @description De persoon of organisatie die dit informatie object heeft aangemaakt */
            auteur: string;
            /** @description Een ISO 639-2/B taalcode waarin de inhoud van het INFORMATIEOBJECT is vastgelegd. Voorbeeld: `dut`. Zie: https://www.iso.org/standard/4767.html */
            taal: string;
            /**
             * Format: date-time
             * @description Een datumtijd in ISO8601 formaat waarop deze versie van het INFORMATIEOBJECT is aangemaakt of gewijzigd.
             */
            beginRegistratie: string;
            /** @description URL-referentie naar het INFORMATIEOBJECTTYPE (in de Catalogi API). */
            informatieobjecttype: string;
            /** @description Aanduiding van de mate waarin het INFORMATIEOBJECT voor de openbaarheid bestemd is. */
            vertrouwelijkheidaanduiding?: string | null;
            /** @description Aanduiding van de stand van zaken van een INFORMATIEOBJECT. */
            status?: string | null;
            /** @description Het "Media Type" (voorheen "MIME type") voor de wijze waaropde inhoud van het INFORMATIEOBJECT is vastgelegd in een computerbestand. Voorbeeld: `application/msword`. Zie: https://www.iana.org/assignments/media-types/media-types.xhtml */
            formaat?: string | null;
            /** @description De naam van het fysieke bestand waarin de inhoud van het informatieobject is vastgelegd, inclusief extensie. */
            bestandsnaam?: string | null;
            /**
             * Format: uri
             * @description De URL waarmee de inhoud van het INFORMATIEOBJECT op te vragen is.
             */
            link?: string | null;
            /** @description Een generieke beschrijving van de inhoud van het INFORMATIEOBJECT. */
            beschrijving?: string | null;
            /** @description De essentiële opmaakaspecten van een INFORMATIEOBJECT. */
            verschijningsvorm?: string | null;
            /** @description Aantal bytes dat de inhoud van INFORMATIEOBJECT in beslag neemt. */
            bestandsomvang?: number | null;
            /**
             * @description De inhoud van het INFORMATIEOBJECT, indien deze is opgenomen in de index.
             * @default
             */
            inhoud: string;
            readonly hasPendingUpdates: boolean;
        };
        DocumentCreate: {
            identificatie?: string;
            bronorganisatie: string;
            /** Format: date */
            creatiedatum: string;
            titel: string;
            auteur: string;
            taal: string;
            /** Format: uri */
            informatieobjecttype: string;
            inhoud?: string;
            bestandsnaam?: string;
            formaat?: string;
            beschrijving?: string;
            vertrouwelijkheidaanduiding?: string;
            status?: string;
            /** Format: uri */
            link?: string;
            trefwoorden?: string[];
        };
        ESDocument: {
            /** @description Unieke resource identifier (UUID4) */
            uuid: string;
            /**
             * Format: uri
             * @description URL-referentie naar dit object. Dit is de unieke identificatie en locatie van dit object.
             */
            url: string;
            /** @description Een binnen een gegeven context ondubbelzinnige referentie naar het INFORMATIEOBJECT. */
            identificatie: string;
            /** @description Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die het informatieobject heeft gecreëerd of heeft ontvangen en als eerste in een samenwerkingsketen heeft vastgelegd. */
            bronorganisatie: string;
            /**
             * Format: date
             * @description Een datum of een gebeurtenis in de levenscyclus van het INFORMATIEOBJECT.
             */
            creatiedatum: string;
            /** @description De naam waaronder het INFORMATIEOBJECT formeel bekend is. */
            titel: string;
            /** @description De persoon of organisatie die dit informatie object heeft aangemaakt */
            auteur: string;
            /** @description Een ISO 639-2/B taalcode waarin de inhoud van het INFORMATIEOBJECT is vastgelegd. Voorbeeld: `dut`. Zie: https://www.iso.org/standard/4767.html */
            taal: string;
            /**
             * Format: date-time
             * @description Een datumtijd in ISO8601 formaat waarop deze versie van het INFORMATIEOBJECT is aangemaakt of gewijzigd.
             */
            beginRegistratie: string;
            /** @description URL-referentie naar het INFORMATIEOBJECTTYPE (in de Catalogi API). */
            informatieobjecttype: string;
            /** @description Aanduiding van de mate waarin het INFORMATIEOBJECT voor de openbaarheid bestemd is. */
            vertrouwelijkheidaanduiding?: string | null;
            /** @description Aanduiding van de stand van zaken van een INFORMATIEOBJECT. */
            status?: string | null;
            /** @description Het "Media Type" (voorheen "MIME type") voor de wijze waaropde inhoud van het INFORMATIEOBJECT is vastgelegd in een computerbestand. Voorbeeld: `application/msword`. Zie: https://www.iana.org/assignments/media-types/media-types.xhtml */
            formaat?: string | null;
            /** @description De naam van het fysieke bestand waarin de inhoud van het informatieobject is vastgelegd, inclusief extensie. */
            bestandsnaam?: string | null;
            /**
             * Format: uri
             * @description De URL waarmee de inhoud van het INFORMATIEOBJECT op te vragen is.
             */
            link?: string | null;
            /** @description Een generieke beschrijving van de inhoud van het INFORMATIEOBJECT. */
            beschrijving?: string | null;
            /** @description De essentiële opmaakaspecten van een INFORMATIEOBJECT. */
            verschijningsvorm?: string | null;
            /** @description Aantal bytes dat de inhoud van INFORMATIEOBJECT in beslag neemt. */
            bestandsomvang?: number | null;
            /**
             * @description De inhoud van het INFORMATIEOBJECT, indien deze is opgenomen in de index.
             * @default
             */
            inhoud: string;
            /** @description De slug van de bronservice die dit document heeft geïndexeerd. */
            serviceSlug?: string | null;
            /** @description De slug van de groep waartoe de bronservice behoort die dit document heeft geïndexeerd. */
            groupSlug?: string | null;
            zaakReferenties?: components["schemas"]["ESZaak"][];
        };
        ESZaak: {
            /**
             * Format: uuid
             * @description UUID van dit object. Dit is de unieke identificatiecode van dit object.
             */
            uuid: string;
            /**
             * Format: uri
             * @description URL-referentie naar dit object. Dit is de unieke identificatie en locatie van dit object.
             */
            url: string;
            /** @description De unieke identificatie van de ZAAK binnen de organisatie die verantwoordelijk is voor de behandeling van de ZAAK. */
            identificatie: string;
            /** @description URL-referentie naar het ZAAKTYPE (in de Catalogi API). */
            zaaktype: string;
            /** @description Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die de zaak heeft gecreeerd. */
            bronorganisatie: string;
            /** @description Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die eindverantwoordelijk is voor de behandeling van de zaak. */
            verantwoordelijkeOrganisatie: string;
            /**
             * Format: date
             * @description De datum waarop de zaakbehandelende organisatie de ZAAK heeft geregistreerd
             */
            registratiedatum: string;
            /**
             * Format: date
             * @description De datum waarop met de uitvoering van de zaak is gestart.
             */
            startdatum: string;
            /** @description Een korte omschrijving van de zaak. */
            omschrijving: string;
            /** @description Een toelichting op de zaak. */
            toelichting: string;
            /** @description De slug van de bronservice die deze zaak heeft geïndexeerd. */
            serviceSlug?: string | null;
            /** @description De slug van de groep waartoe de bronservice behoort die deze zaak heeft geïndexeerd. */
            groupSlug?: string | null;
            /** @description De slug van de ZTC service die gekoppeld is aan de bronservice die deze zaak heeft geïndexeerd. */
            ztcServiceSlug?: string | null;
            /** @description De UUID van de zaak in de ZTC, indien deze bekend is en gekoppeld kan worden. */
            ztcUuid?: string | null;
            /** @description Het jaar waarin de zaak is gestart. Dit veld is optioneel en kan worden gebruikt voor aanvullende filtering of sortering op jaarniveau. */
            startjaar?: string | null;
        };
        /** @description Formaat van validatiefouten. */
        FieldValidationError: {
            /** @description Naam van het veld met ongeldige gegevens */
            name: string;
            /** @description Systeemcode die het type fout aangeeft */
            code: string;
            /** @description Uitleg wat er precies fout is met de gegevens */
            reason: string;
        };
        /** @description Formaat van HTTP 4xx en 5xx fouten. */
        Fout: {
            /** @description URI referentie naar het type fout, bedoeld voor developers */
            type?: string;
            /** @description Systeemcode die het type fout aangeeft */
            code: string;
            /** @description Generieke titel voor het type fout */
            title: string;
            /** @description De HTTP status code */
            status: number;
            /** @description Extra informatie bij de fout, indien beschikbaar */
            detail: string;
            /** @description URI met referentie naar dit specifiek voorkomen van de fout. Deze kan gebruikt worden in combinatie met server logs, bijvoorbeeld. */
            instance: string;
        };
        InformatieObjectType: {
            /** Format: uuid */
            uuid: string;
            /** Format: uri */
            url: string;
            /** Format: uri */
            catalogus: string;
            omschrijving: string;
            vertrouwelijkheidaanduiding: string;
            /** Format: date */
            beginGeldigheid?: string | null;
            /** Format: date */
            eindeGeldigheid?: string | null;
            concept: boolean;
            informatieobjectcategorie: string;
            zaaktypen: string[];
        };
        PaginatedDocumentList: {
            /** @example 123 */
            count: number;
            results: components["schemas"]["Document"][];
        };
        PaginatedServiceList: {
            /** @example 123 */
            count: number;
            results: components["schemas"]["Service"][];
        };
        PaginatedStatusTypeList: {
            /** @example 123 */
            count: number;
            results: components["schemas"]["StatusType"][];
        };
        PaginatedZaakInformatieObjectCreateList: {
            /** @example 123 */
            count: number;
            results: components["schemas"]["ZaakInformatieObjectCreate"][];
        };
        PaginatedZaakList: {
            /** @example 123 */
            count: number;
            results: components["schemas"]["Zaak"][];
        };
        PaginatedZaakTypeList: {
            /** @example 123 */
            count: number;
            results: components["schemas"]["ZaakType"][];
        };
        Search: {
            /**
             * @description Filtering records based on the provided search term. The search is performed across both Documents and Zaken index.This search is applied to the following fields:
             *
             *     **Documents:**
             *     - `identificatie`
             *     - `titel`
             *     - `bronorganisatie`
             *     - `beschrijving`
             *     - `document_data.attachment.content`
             *
             *     - `zaak_referenties.identificatie`
             *     - `zaak_referenties.omschrijving`
             *     - `zaak_referenties.toelichting`
             *     - `zaak_referenties.status`
             *
             *     **Zaken:**
             *     - `identificatie`
             *     - `omschrijving`
             *     - `toelichting`
             *     - `status`
             *
             *     You can use double quotes for exact matches and `AND`/`OR` syntax for complex queries.
             * @default
             */
            query: string;
            /**
             * @description Page number.
             * @default 1
             */
            page: number;
            /**
             * @description Number of results per page.
             * @default 10
             */
            pageSize: number;
            /** @default relevance */
            sort: components["schemas"]["SortEnum"];
            /**
             * Format: date
             * @description Filter documents created on or after this date.
             */
            creatiedatumVanaf?: string | null;
            /**
             * Format: date
             * @description Filter documents created on or before this date.
             */
            creatiedatumTotEnMet?: string | null;
        };
        SearchResponse: {
            count: number;
            results: components["schemas"]["SearchResult"][];
        };
        SearchResult: components["schemas"]["SearchResultDocument"] | components["schemas"]["SearchResultZaak"];
        SearchResultDocument: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "document";
            data: components["schemas"]["ESDocument"];
        };
        /** @enum {string} */
        SearchResultDocumentTypeEnum: "document";
        SearchResultZaak: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "zaak";
            data: components["schemas"]["ESZaak"];
        };
        /** @enum {string} */
        SearchResultZaakTypeEnum: "zaak";
        Service: {
            /**
             * Service slug
             * @description A unique, human-friendly slug to identify this service. Primarily useful for cross-instance import/export.
             */
            slug: string;
            label: string;
        };
        /** @enum {string} */
        SortEnum: "relevance" | "chronological";
        StatusType: {
            /**
             * Format: uuid
             * @description UUID van dit object. Dit is de unieke identificatiecode van dit object.
             */
            uuid: string;
            /**
             * Format: uri
             * @description URL-referentie naar dit object. Dit is de unieke identificatie en locatie van dit object.
             */
            url: string;
            /** @description Een korte, voor de initiator van de zaak relevante, omschrijving van de aard van de STATUS van zaken van een ZAAKTYPE. */
            omschrijving: string;
            /** @description Algemeen gehanteerde omschrijving van de aard van STATUSsen van het STATUSTYPE. */
            omschrijvingGeneriek?: string;
            /** @description De tekst die wordt gebruikt om de Initiator te informeren over het bereiken van een STATUS van dit STATUSTYPE bij het desbetreffende ZAAKTYPE. */
            statustekst?: string;
            /**
             * Format: uri
             * @description URL-referentie naar het ZAAKTYPE van ZAAKen waarin STATUSsen van dit STATUSTYPE bereikt kunnen worden.
             */
            zaaktype: string;
            /**
             * Format: uri
             * @description URL-referentie naar de CATALOGUS waartoe dit STATUSTYPE behoort.
             */
            catalogus: string;
            /** @description Unieke identificatie van het ZAAKTYPE binnen de CATALOGUS waarin het ZAAKTYPE voorkomt. */
            zaaktypeIdentificatie: string;
            /** @description Een volgnummer voor statussen van het STATUSTYPE binnen een zaak. */
            volgnummer: number;
            /** @description Geeft aan dat dit STATUSTYPE een eindstatus betreft. */
            isEindstatus: boolean;
            /** @description Aanduiding die aangeeft of na het zetten van een STATUS van dit STATUSTYPE de Initiator moet worden geïnformeerd over de statusovergang. */
            informeren: boolean;
            /** @description De door de zaakbehandelende organisatie(s) gestelde norm voor de doorlooptijd voor het bereiken van STATUSsen van dit STATUSTYPE. */
            doorlooptijd?: string | null;
            /** @description Een eventuele toelichting op dit STATUSTYPE. */
            toelichting?: string | null;
            /** @description De checklistitems behorend bij dit STATUSTYPE. */
            checklistitemStatustype?: components["schemas"]["CheckListItem"][];
            /** @description De EIGENSCHAPpen die verplicht een waarde moeten hebben gekregen, voordat een STATUS van dit STATUSTYPE kan worden gezet. */
            eigenschappen?: (string | null)[];
        };
        User: {
            /** ID */
            readonly pk: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            firstName?: string;
            lastName?: string;
            /**
             * Email address
             * Format: email
             */
            email?: string;
        };
        /** @description Formaat van HTTP 4xx en 5xx fouten. */
        ValidatieFout: {
            /** @description URI referentie naar het type fout, bedoeld voor developers */
            type?: string;
            /** @description Systeemcode die het type fout aangeeft */
            code: string;
            /** @description Generieke titel voor het type fout */
            title: string;
            /** @description De HTTP status code */
            status: number;
            /** @description Extra informatie bij de fout, indien beschikbaar */
            detail: string;
            /** @description URI met referentie naar dit specifiek voorkomen van de fout. Deze kan gebruikt worden in combinatie met server logs, bijvoorbeeld. */
            instance: string;
            invalidParams: components["schemas"]["FieldValidationError"][];
        };
        WhoAmI: {
            isAuthenticated: boolean;
            readonly user: components["schemas"]["User"];
        };
        Zaak: {
            /**
             * Format: uuid
             * @description UUID van dit object. Dit is de unieke identificatiecode van dit object.
             */
            uuid: string;
            /**
             * Format: uri
             * @description URL-referentie naar dit object. Dit is de unieke identificatie en locatie van dit object.
             */
            url: string;
            /** @description De unieke identificatie van de ZAAK binnen de organisatie die verantwoordelijk is voor de behandeling van de ZAAK. */
            identificatie: string;
            /** @description URL-referentie naar het ZAAKTYPE (in de Catalogi API). */
            zaaktype: string;
            /** @description Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die de zaak heeft gecreeerd. */
            bronorganisatie: string;
            /** @description Het RSIN van de Niet-natuurlijk persoon zijnde de organisatie die eindverantwoordelijk is voor de behandeling van de zaak. */
            verantwoordelijkeOrganisatie: string;
            /**
             * Format: date
             * @description De datum waarop de zaakbehandelende organisatie de ZAAK heeft geregistreerd
             */
            registratiedatum: string;
            /**
             * Format: date
             * @description De datum waarop met de uitvoering van de zaak is gestart.
             */
            startdatum: string;
            /** @description Een korte omschrijving van de zaak. */
            omschrijving: string;
            /** @description Een toelichting op de zaak. */
            toelichting: string;
        };
        ZaakCreate: {
            /** Format: uri */
            zaaktype: string;
            omschrijving?: string;
            /** Format: date */
            startdatum: string;
            bronorganisatie: string;
            verantwoordelijkeOrganisatie: string;
        };
        ZaakInformatieObjectCreate: {
            /** Format: uri */
            zaak: string;
            /** Format: uri */
            informatieobject: string;
            titel?: string;
            beschrijving?: string;
        };
        ZaakType: {
            /**
             * Format: uuid
             * @description UUID van dit object. Dit is de unieke identificatiecode van dit object.
             */
            uuid: string;
            /**
             * Format: uri
             * @description URL-referentie naar dit object. Dit is de unieke identificatie en locatie van dit object.
             */
            url: string;
            /**
             * Format: uri
             * @description URL-referentie naar de CATALOGUS waartoe dit ZAAKTYPE behoort.
             */
            catalogus: string;
            /** @description Geeft aan of het object een concept betreft. Concepten zijn niet-definitieve versies en zouden niet gebruikt moeten worden buiten deze API. */
            concept: boolean;
            /** @description Unieke identificatie van het ZAAKTYPE binnen de CATALOGUS waarin het ZAAKTYPE voorkomt. */
            identificatie: string;
            /** @description Omschrijving van de aard van ZAAKen van het ZAAKTYPE. */
            omschrijving: string;
            /**
             * Format: date
             * @description De datum waarop de (gewijzigde) kenmerken van het ZAAKTYPE geldig zijn geworden
             */
            versiedatum: string;
            /**
             * Format: date
             * @description De datum waarop het is ontstaan.
             */
            beginGeldigheid: string;
            /**
             * Format: date
             * @description De datum waarop het is opgeheven.
             */
            eindeGeldigheid: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apiV1AccountsLoginCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Auth"];
            };
        };
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmI"];
                };
            };
            400: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidatieFout"];
                };
            };
            403: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Fout"];
                };
            };
        };
    };
    apiV1AccountsLogoutRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apiV1AccountsWhoamiRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmI"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Search"];
            };
        };
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    apiV1ServicesList: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Het aantal resultaten terug te geven per pagina. (default: 100, maximum: 500). */
                pageSize?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedServiceList"];
                };
            };
        };
    };
    apiV1ServicesInformatieobjecttypenList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InformatieObjectType"][];
                };
            };
        };
    };
    apiV1ServicesInformatieobjecttypenRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                informatieobjecttypeUuid: string;
                serviceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InformatieObjectType"];
                };
            };
        };
    };
    apiV1ServicesStatustypenList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusType"][];
                };
            };
        };
    };
    apiV1ServicesStatustypenRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceSlug: string;
                statustypeUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusType"];
                };
            };
        };
    };
    apiV1ServicesZaakinformatieobjectenList: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Het aantal resultaten terug te geven per pagina. (default: 100, maximum: 500). */
                pageSize?: number;
            };
            header?: never;
            path: {
                serviceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedZaakInformatieObjectCreateList"];
                };
            };
        };
    };
    apiV1ServicesZaakinformatieobjectenCreate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZaakInformatieObjectCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    apiV1ServicesZaakinformatieobjectenRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                serviceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZaakInformatieObjectCreate"];
                };
            };
        };
    };
    apiV1ServicesZaaktypenList: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Het aantal resultaten terug te geven per pagina. (default: 100, maximum: 500). */
                pageSize?: number;
                /** @description A search term for the ZaakType service. The search is performed against the `identificatie__icontains` field. */
                search?: string;
            };
            header?: never;
            path: {
                serviceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedZaakTypeList"];
                };
            };
        };
    };
    apiV1ServicesZaaktypenRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceSlug: string;
                zaaktypeUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZaakType"];
                };
            };
        };
    };
    apiV1ServicesZaaktypenStatustypenList: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Het aantal resultaten terug te geven per pagina. (default: 100, maximum: 500). */
                pageSize?: number;
            };
            header?: never;
            path: {
                serviceSlug: string;
                zaaktypenZaaktypeUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedStatusTypeList"];
                };
            };
        };
    };
    apiV1ServicesZaaktypenStatustypenRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceSlug: string;
                statustypeUuid: string;
                zaaktypenZaaktypeUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusType"];
                };
            };
        };
    };
    apiV1ServicesZaaktypenZakenList: {
        parameters: {
            query?: {
                /** @description De datum waarop de uitvoering van de zaak afgerond is. */
                einddatum__isnull?: boolean;
                /** @description De unieke identificatie van de ZAAK (bevat de identificatie de gegeven waarden (hoofdletterongevoelig)) */
                identificatie__icontains?: string;
                /** @description Een korte omschrijving van de ZAAK (bevat de omschrijving de gegeven waarden (hoofdletterongevoelig)) */
                omschrijving?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Het aantal resultaten terug te geven per pagina. (default: 100, maximum: 500). */
                pageSize?: number;
                /** @description De datum waarop met de uitvoering van de zaak is gestart */
                startdatum__gte?: string;
            };
            header?: never;
            path: {
                serviceSlug: string;
                zaaktypenZaaktypeUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedZaakList"];
                };
            };
        };
    };
    apiV1ServicesZaaktypenZakenRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceSlug: string;
                zaakUuid: string;
                zaaktypenZaaktypeUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zaak"];
                };
            };
        };
    };
    apiV1ServicesZaaktypenZakenDocumentsList: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Het aantal resultaten terug te geven per pagina. (default: 100, maximum: 500). */
                pageSize?: number;
            };
            header?: never;
            path: {
                serviceSlug: string;
                zaaktypenZaaktypeUuid: string;
                zakenZaakUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocumentList"];
                };
            };
        };
    };
    apiV1ServicesZaaktypenZakenDocumentsCreate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceSlug: string;
                zaaktypenZaaktypeUuid: string;
                zakenZaakUuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    apiV1ServicesZaaktypenZakenDocumentsRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentUuid: string;
                serviceSlug: string;
                zaaktypenZaaktypeUuid: string;
                zakenZaakUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    documentDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentUuid: string;
                serviceSlug: string;
                zaaktypenZaaktypeUuid: string;
                zakenZaakUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description De binaire bestandsinhoud */
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
        };
    };
    documentEdit: {
        parameters: {
            query?: {
                /** @description URL to redirect to in case of a renewed authentication flow */
                originUrl?: string;
            };
            header?: never;
            path: {
                documentUuid: string;
                serviceSlug: string;
                zaaktypenZaaktypeUuid: string;
                zakenZaakUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Editor URL as a body */
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication URL as body */
            403: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Empty body, document is locked */
            423: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    documentUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documentUuid: string;
                serviceSlug: string;
                zaaktypenZaaktypeUuid: string;
                zakenZaakUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    apiV1ServicesZakenList: {
        parameters: {
            query?: {
                /** @description De unieke identificatie van de ZAAK (bevat de identificatie de gegeven waarden (hoofdletterongevoelig)) */
                identificatie__icontains?: string;
                /** @description Een korte omschrijving van de ZAAK (bevat de omschrijving de gegeven waarden (hoofdletterongevoelig)) */
                omschrijving?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Het aantal resultaten terug te geven per pagina. (default: 100, maximum: 500). */
                pageSize?: number;
                /** @description De datum waarop met de uitvoering van de zaak is gestart */
                startdatum__gte?: string;
            };
            header?: never;
            path: {
                serviceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedZaakList"];
                };
            };
        };
    };
    apiV1ServicesZakenCreate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceSlug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZaakCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zaak"];
                };
            };
        };
    };
    apiV1ServicesZakenRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceSlug: string;
                zaakUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Zaak"];
                };
            };
        };
    };
    apiV1ServicesRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
        };
    };
    oidcCallbackRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect naar de oorspronkelijke URL na succesvolle authenticatie */
            302: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid callback of fout tijdens authenticatie */
            400: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticatie mislukt (geen access token) */
            401: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    webhookCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Webhook verwerkt */
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Ongeldige payload */
            400: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
