/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * login
         * @description Authenticates the user, returns whoami details on successful login.
         */
        post: operations["apiV1AccountsLoginCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * logout
         * @description Remove the authenticated user's ID from the request and flush their session data.
         */
        get: operations["apiV1AccountsLogoutRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * whoami
         * @description Returns the current logged in user.
         */
        get: operations["apiV1AccountsWhoamiRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documenten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Index document metadata.
         * @description Index the received document metadata from the Register API in Elasticsearch.
         */
        post: operations["apiV1DocumentenCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documenten/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove document from index.
         * @description Remove the referenced document data from the index.
         *     This schedules a background task to perform the actual removal.
         */
        delete: operations["apiV1DocumentenDestroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description Search the document records.
         */
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1ServicesList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaaktypen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Exposes Zaaktypen from a ZGW service. */
        get: operations["apiV1ServicesZaaktypenList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{serviceSlug}/zaaktypen/{zaaktypeUuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Exposes Zaaktypen from a ZGW service. */
        get: operations["apiV1ServicesZaaktypenRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/services/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["apiV1ServicesRetrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Auth: {
            username: string;
            password: string;
        };
        CeleryTaskId: {
            /** Format: uuid */
            taskId: string;
        };
        Document: {
            uuid: string;
            /** Format: uri */
            url: string;
            identificatie: string;
            bronorganisatie: string;
            /** Format: date */
            creatiedatum: string;
            titel: string;
            auteur: string;
            taal: string;
            /** Format: date-time */
            beginRegistratie: string;
            informatieobjecttype: string;
            vertrouwelijkheidaanduiding?: string | null;
            status?: string | null;
            formaat?: string | null;
            bestandsnaam?: string | null;
            /** Format: uri */
            link?: string | null;
            beschrijving?: string | null;
            /** Format: date */
            ontvangstdatum?: string | null;
            /** Format: date */
            verzenddatum?: string | null;
            verschijningsvorm?: string | null;
            bestandsomvang?: number | null;
            /** @default  */
            inhoud: string;
        };
        DocumentIndex: {
            uuid: string;
            /** Format: uri */
            url: string;
            identificatie: string;
            bronorganisatie: string;
            /** Format: date */
            creatiedatum: string;
            titel: string;
            auteur: string;
            taal: string;
            /** Format: date-time */
            beginRegistratie: string;
            informatieobjecttype: string;
            vertrouwelijkheidaanduiding?: string | null;
            status?: string | null;
            formaat?: string | null;
            bestandsnaam?: string | null;
            /** Format: uri */
            link?: string | null;
            beschrijving?: string | null;
            /** Format: date */
            ontvangstdatum?: string | null;
            /** Format: date */
            verzenddatum?: string | null;
            verschijningsvorm?: string | null;
            bestandsomvang?: number | null;
            /** Format: uri */
            inhoud?: string;
        };
        DocumentResult: {
            readonly record: components["schemas"]["Document"];
        };
        /** @description Formaat van validatiefouten. */
        FieldValidationError: {
            /** @description Naam van het veld met ongeldige gegevens */
            name: string;
            /** @description Systeemcode die het type fout aangeeft */
            code: string;
            /** @description Uitleg wat er precies fout is met de gegevens */
            reason: string;
        };
        PaginatedServiceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Service"][];
        };
        PaginatedZaakTypeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ZaakType"][];
        };
        Search: {
            /**
             * @description Filtering records based on the provided search term. This search is applied to the following fields:
             *
             *     - `identificatie`
             *     - `titel`
             *     - `bronorganisatie`
             *     - `beschrijving`
             *     - `document_data.attachment.content`
             *
             *     You can use double quotes for exact matches and `AND`/`OR` syntax for complex queries.
             * @default
             */
            query: string;
            /**
             * @description Page number.
             * @default 1
             */
            page: number;
            /**
             * @description Number of results per page.
             * @default 10
             */
            pageSize: number;
            /** @default relevance */
            sort: components["schemas"]["SortEnum"];
            /**
             * Format: date
             * @description Filter documents created on or after this date.
             */
            creatiedatumVanaf?: string | null;
            /**
             * Format: date
             * @description Filter documents created on or before this date.
             */
            creatiedatumTotEnMet?: string | null;
        };
        SearchResponse: {
            count: number;
            readonly next: boolean;
            readonly previous: boolean;
            results: components["schemas"]["SearchResults"][];
        };
        SearchResults: components["schemas"]["SearchResultsDocumentResult"];
        SearchResultsDocumentResult: components["schemas"]["SearchResultsShared"] & components["schemas"]["DocumentResult"] & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "document";
        };
        /**
         * @description Polymorphic serializer base class.
         *
         *     Note that the discriminator field must exist at the same depth as the mapped
         *     serializer fields for the OpenAPI introspection. See
         *     https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/ for
         *     more information. As such, it's not possible to define something like:
         *
         *     {
         *         "object_type": "foo",
         *         "polymorphic_context": {
         *             <foo-specific fields>
         *         }
         *     }
         *
         *     without explicitly wrapping this in a parent serializer, i.e. -
         *     ``polymorphic_context`` can not be a PolymorphicSerializer itself, as it requires
         *     access to the ``object_type`` in the parent scope.
         */
        SearchResultsShared: {
            type: string;
        };
        Service: {
            /**
             * Service slug
             * @description A unique, human-friendly slug to identify this service. Primarily useful for cross-instance import/export.
             */
            slug: string;
            label: string;
        };
        /** @enum {string} */
        SortEnum: "relevance" | "chronological";
        User: {
            /** ID */
            readonly pk: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            firstName?: string;
            lastName?: string;
            /**
             * Email address
             * Format: email
             */
            email?: string;
        };
        /** @description Formaat van HTTP 4xx en 5xx fouten. */
        ValidatieFout: {
            /** @description URI referentie naar het type fout, bedoeld voor developers */
            type?: string;
            /** @description Systeemcode die het type fout aangeeft */
            code: string;
            /** @description Generieke titel voor het type fout */
            title: string;
            /** @description De HTTP status code */
            status: number;
            /** @description Extra informatie bij de fout, indien beschikbaar */
            detail: string;
            /** @description URI met referentie naar dit specifiek voorkomen van de fout. Deze kan gebruikt worden in combinatie met server logs, bijvoorbeeld. */
            instance: string;
            invalidParams: components["schemas"]["FieldValidationError"][];
        };
        WhoAmI: {
            isAuthenticated: boolean;
            readonly user: components["schemas"]["User"];
        };
        ZaakType: {
            /**
             * Format: uuid
             * @description UUID van dit object. Dit is de unieke identificatiecode van dit object.
             */
            uuid: string;
            /**
             * Format: uri
             * @description URL-referentie naar de CATALOGUS waartoe dit ZAAKTYPE behoort.
             */
            catalogus: string;
            /** @description Unieke identificatie van het ZAAKTYPE binnen de CATALOGUS waarin het ZAAKTYPE voorkomt. */
            identificatie: string;
            /** @description Omschrijving van de aard van ZAAKen van het ZAAKTYPE. */
            omschrijving: string;
            /**
             * Format: date
             * @description De datum waarop het is ontstaan.
             */
            beginGeldigheid: string;
            /**
             * Format: date
             * @description De datum waarop het is opgeheven.
             */
            eindeGeldigheid: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apiV1AccountsLoginCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Auth"];
            };
        };
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmI"];
                };
            };
            400: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidatieFout"];
                };
            };
        };
    };
    apiV1AccountsLogoutRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    apiV1AccountsWhoamiRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmI"];
                };
            };
        };
    };
    apiV1DocumentenCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentIndex"];
            };
        };
        responses: {
            202: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CeleryTaskId"];
                };
            };
        };
    };
    apiV1DocumentenDestroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the document to remove */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CeleryTaskId"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Search"];
            };
        };
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"][];
                };
            };
        };
    };
    apiV1ServicesList: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Het aantal resultaten terug te geven per pagina. (default: 100, maximum: 500). */
                pageSize?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedServiceList"];
                };
            };
        };
    };
    apiV1ServicesZaaktypenList: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Het aantal resultaten terug te geven per pagina. (default: 100, maximum: 500). */
                pageSize?: number;
            };
            header?: never;
            path: {
                serviceSlug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedZaakTypeList"];
                };
            };
        };
    };
    apiV1ServicesZaaktypenRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                serviceSlug: string;
                zaaktypeUuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZaakType"];
                };
            };
        };
    };
    apiV1ServicesRetrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    /** @description Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1. */
                    "API-version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Service"];
                };
            };
        };
    };
}
