# Generated by Django 5.2.12 on 2026-04-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraphSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscription_id", models.CharField(max_length=255, unique=True)),
                ("client_state", models.CharField(max_length=255)),
                ("resource", models.CharField(max_length=255)),
                ("notification_url", models.CharField(max_length=500)),
                ("expiration_date_time", models.DateTimeField()),
                ("delta_url", models.CharField(blank=True, max_length=500)),
                ("token", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "graph_subscriptions",
            },
        ),
    ]
