# Generated by Django 5.2.12 on 2026-04-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseDriveDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="The unique identifier of the file on the storage provider.",
                        max_length=255,
                    ),
                ),
                (
                    "document_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The display name of the file as it appears on the storage provider.",
                        max_length=255,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was first created in the local database.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last detected modification on the remote file. Null if never updated.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "base drive document",
                "verbose_name_plural": "base drive documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BaseDriveSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(
                        help_text="Unique identifier returned by the storage provider when the subscription is created.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "client_state",
                    models.CharField(
                        help_text="Secret string used to validate that notifications are coming from the storage provider.",
                        max_length=255,
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        help_text="The resource path being monitored, e.g. '/me/drive/root/'.",
                        max_length=255,
                    ),
                ),
                (
                    "notification_url",
                    models.CharField(
                        help_text="The webhook URL where the storage provider sends change notifications.",
                        max_length=500,
                    ),
                ),
                (
                    "expiration_date_time",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Expiration timestamp of the subscription. Must be renewed before this date.",
                    ),
                ),
                (
                    "delta_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The deltaLink URL returned by the last delta query. Used to fetch only changed items.",
                        max_length=500,
                    ),
                ),
                (
                    "token",
                    models.TextField(
                        help_text="OAuth2 access token used to authenticate requests to the storage provider."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "base drive subscription",
                "verbose_name_plural": "base drive subscriptions",
                "ordering": ["-created_at"],
            },
        ),
    ]
