# Generated by Django 5.2.12 on 2026-04-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc_edit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basedrivedocument",
            name="synced_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of the last synchronized.", null=True
            ),
        ),
    ]
