# Generated by Django 5.2.12 on 2026-04-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc_edit", "0002_basedrivedocument_synced_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="basedrivedocument",
            name="etag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
