# Generated by Django 5.2.12 on 2026-04-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doc_edit", "0003_basedrivedocument_etag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basedrivedocument",
            name="etag",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
